It is a multiclass classification problem, We are going to buil a text generator, supervised learning problem - for example - (a) hi my name is palak, (b) I live in Odisha.
As soon as I type **hi**, the model should predict next word **my** and further when **hi my** appears the model should predict **name** and so on. here **hi** and **hi my** were my input. But we need to convert this words to numbers.

In [76]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [77]:
faqs = """About the Program
What is the course fee for Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.comPayment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.comPost registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessionsSoft skill sessionsSessions with industry mentorsDiscussion on Job hunting strategies"""

Converting words to numbers

In [78]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [79]:
tokenizer = Tokenizer()

In [80]:
# input should be sent to a list, as there are multiple words
tokenizer.fit_on_texts([faqs])

In [81]:
tokenizer.word_index
# this way unique tokens will get an index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'on': 17,
 'be': 18,
 'and': 19,
 'this': 20,
 'if': 21,
 'am': 22,
 'pay': 23,
 'make': 24,
 'we': 25,
 'do': 26,
 'payment': 27,
 'subscription': 28,
 'where': 29,
 'rs': 30,
 'so': 31,
 'campusx': 32,
 'session': 33,
 'our': 34,
 'sessions': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'mail': 60,
 'from': 61,
 'contact': 62,
 'us': 63,
 'at': 64,
 'or': 65,
 'doubt': 66,
 'mentorship': 67,
 'payments': 68,
 '799': 69,
 'total': 70,
 'duration': 71,
 'months': 72,
 'learning': 73,
 'case': 74,
 'here': 75,
 'https': 76,


In [82]:
# now we will find out all the sentences present in our dataset
#for sentence in faqs.split('\n'):
#splitting the dataset on the basis of line change
  #print(sentence)
  #print(tokenizer.texts_to_sequences([sentence])[0])

now we need to generate inputs ad outputs, as in for the first sentence[92,1,13]-> [92] will be the input to which [1] should be the output, further [92,1] should be the input and [13] should be the output.

In [83]:
input_sequences = []

for sentence in faqs.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1, len(tokenized_sentence)):
       input_sequences.append(tokenized_sentence[:i+1])

1. List to store input sequences
2. Generate input sequences for each sentence
3. for any sentence the loop will run for (no. of words - 1) times.
4. at first the loop runs for i=1, first index....then it will take i+1=2, run for first 2 index and so on.

In [84]:
input_sequences

[[92, 1],
 [92, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 42],
 [11, 7, 1, 12, 42, 15],
 [11, 7, 1, 12, 42, 15, 43],
 [11, 7, 1, 12, 42, 15, 43, 53],
 [11, 7, 1, 12, 42, 15, 43, 53, 67],
 [11, 7, 1, 12, 42, 15, 43, 53, 67, 13],
 [11, 7, 1, 12, 42, 15, 43, 53, 67, 13, 147],
 [11, 7, 1, 12, 42, 15, 43, 53, 67, 13, 147, 148],
 [1, 12],
 [1, 12, 93],
 [1, 12, 93, 5],
 [1, 12, 93, 5, 44],
 [1, 12, 93, 5, 44, 28],
 [1, 12, 93, 5, 44, 28, 94],
 [1, 12, 93, 5, 44, 28, 94, 29],
 [1, 12, 93, 5, 44, 28, 94, 29, 2],
 [1, 12, 93, 5, 44, 28, 94, 29, 2, 8],
 [1, 12, 93, 5, 44, 28, 94, 29, 2, 8, 4],
 [1, 12, 93, 5, 44, 28, 94, 29, 2, 8, 4, 24],
 [1, 12, 93, 5, 44, 28, 94, 29, 2, 8, 4, 24, 44],
 [1, 12, 93, 5, 44, 28, 94, 29, 2, 8, 4, 24, 44, 68],
 [1, 12, 93, 5, 44, 28, 94, 29, 2, 8, 4, 24, 44, 68, 6],
 [1, 12, 93, 5, 44, 28, 94, 29, 2, 8, 4, 24, 44, 68, 6, 30],
 [1, 12, 93, 5, 44, 28, 94, 29, 2, 8, 4, 24, 44, 68, 6, 30, 69],
 [1, 12, 93, 5, 44, 28, 94, 29, 2, 8, 4, 24, 44, 68, 6

Now we will be zero padding the above output, this will add zeroes to every index, equal to the number of maximum words in any row.

In [85]:
#finding length of every sentence and adding them to a list, then choosing the maximum one
max_length = max([len(x) for x in input_sequences])

In [86]:
max_length

57

In [87]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_length, padding='pre')

In [88]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  92,   1],
       [  0,   0,   0, ...,  92,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 280,  17, 281],
       [  0,   0,   0, ...,  17, 281, 282],
       [  0,   0,   0, ..., 281, 282, 283]], dtype=int32)

now we can separate our input and output sequences, in each row -> input will be from (0 to (n-2)) column, and output will be (n-1)th column

In [89]:
x = padded_input_sequences[:,:-1]

In [90]:
y = padded_input_sequences[:,-1]

 as it is a classification problem, we will transform our output and replacing outputs with their one hot encoded representation -> if there are 9 words the representation for 2 will be [0 1 0 0 0 0 0 0 0]

In [91]:
x.shape

(863, 56)

In [92]:
y.shape

(863,)

In [93]:
len(tokenizer.word_index)

283

In [94]:
# we need to one hot encode y, as it is scalar for now
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes =284)      # num_classes = total number of words
# 284 because, one hot encoding starts from zero always, but here it is starting from 1 so we need to add 1 to the length

In [95]:
y.shape
# every output is 284 number long sequence

(863, 284)

In [96]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

now we will build the architecture of our lstm model, 3layers(embedding, lstm, dense)

In [97]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [98]:
model = Sequential()

model.add(Embedding(284, 100, input_length = 56))
model.add(LSTM(150))
model.add(Dense(284, activation='softmax'))

In [99]:
model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [100]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 56, 100)           28400     
                                                                 
 lstm_2 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 284)               42884     
                                                                 
Total params: 221884 (866.73 KB)
Trainable params: 221884 (866.73 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In case of embedding - every input of 56 words, is given 100 numbers as output that is why weights is 284*100, this is conversion to 100D vector.
In case of LSTM - each 100D vector of a word will be input to the first timestep at t=1, then at t=2 second word will be the input.. this will go on till t=56, and the output will be of dimension(1,150)as the number of nodes in lstm is 150 so the dimension will be 150.
In case of dense - contains 284 nodes, which will give 284 output in the range of (0-1)(due to softmax which acts as probability), and the one with max probability will be our output.

In [101]:
model.fit(x,y, epochs = 10)
# you can increase the number of epochs to 100 to increase the accuracy

Epoch 1/10
27/27 [==============================] - 7s 137ms/step - loss: 5.4692 - accuracy: 0.0579
Epoch 2/10
27/27 [==============================] - 3s 98ms/step - loss: 5.1028 - accuracy: 0.0776
Epoch 3/10
27/27 [==============================] - 3s 100ms/step - loss: 5.0328 - accuracy: 0.0776
Epoch 4/10
27/27 [==============================] - 3s 98ms/step - loss: 5.0064 - accuracy: 0.0776
Epoch 5/10
27/27 [==============================] - 5s 174ms/step - loss: 4.9622 - accuracy: 0.0776
Epoch 6/10
27/27 [==============================] - 3s 113ms/step - loss: 4.8923 - accuracy: 0.0776
Epoch 7/10
27/27 [==============================] - 3s 97ms/step - loss: 4.7647 - accuracy: 0.0846
Epoch 8/10
27/27 [==============================] - 3s 98ms/step - loss: 4.5726 - accuracy: 0.1275
Epoch 9/10
27/27 [==============================] - 3s 97ms/step - loss: 4.3374 - accuracy: 0.1541
Epoch 10/10
27/27 [==============================] - 5s 186ms/step - loss: 4.0613 - accuracy: 0.2074


In [110]:
# now comes the prediction part, where we will give a word as input and the model will predict its next word
text = "nlp and deep learning"

#tokenize
token_text = tokenizer.texts_to_sequences([text])[0]
#padding
padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
print(padded_token_text)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 101  19
  100  73]]


In [111]:
#predict
model.predict(padded_token_text)

1/1 [==============================] - 0s 30ms/step


array([[2.6424532e-05, 3.3122271e-02, 1.7784543e-02, 5.7499982e-02,
        1.8516187e-02, 8.2923271e-02, 1.4125387e-02, 2.0286042e-02,
        2.8377822e-02, 1.7871378e-02, 3.1124404e-02, 2.6430769e-03,
        4.6577863e-03, 3.9307438e-03, 9.7751478e-03, 7.1392418e-03,
        1.3303883e-02, 3.7574244e-03, 2.1805201e-02, 1.7802862e-02,
        6.6743717e-03, 1.0679102e-02, 3.0321131e-02, 1.1263053e-02,
        9.3953758e-03, 1.1587123e-02, 1.4130952e-02, 3.8023882e-03,
        1.9543341e-03, 4.4388970e-04, 2.4975019e-03, 5.2631916e-03,
        2.0795874e-03, 2.0973175e-03, 5.0355331e-03, 3.5602988e-03,
        1.9913164e-03, 1.7846977e-02, 1.1246286e-02, 3.9990083e-03,
        1.5054779e-03, 8.2157170e-03, 3.2604979e-03, 5.2352296e-03,
        4.0489985e-03, 2.9781628e-03, 1.2206608e-02, 1.3488477e-02,
        3.9671628e-05, 5.6584561e-03, 1.9822756e-03, 2.7166260e-03,
        9.2675807e-03, 2.7678190e-03, 3.3860717e-03, 1.6655420e-03,
        1.3600166e-02, 6.4969850e-03, 3.3603401e

In [112]:
model.predict(padded_token_text).shape

1/1 [==============================] - 0s 49ms/step


(1, 284)

In [114]:
import numpy as np
pos = np.argmax(model.predict(padded_token_text))
# this will give the number of word with maximum probability


1/1 [==============================] - 0s 35ms/step


In [115]:
for word,index in tokenizer.word_index.items():
  if index == pos:
    print(word)
# this is a loop to predict only one word

a


In [120]:
# if we want to predict next 5 words, we can run a loop
import time
text = "mail"
for i in range(10):
#tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
#padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
#predict
  pos = np.argmax(model.predict(padded_token_text))

# Find the word corresponding to the predicted index

for word, index in tokenizer.word_index.items():
  if index == pos:
    predicted_word = text
    break

    # If a word was found, append it to the text
  if predicted_word:
    text = text + " " + predicted_word
    print(text)
  else:
    print("Predicted word not found in the tokenizer's word index.")
    break

time.sleep(1)

1/1 [==============================] - 0s 30ms/step
Predicted word not found in the tokenizer's word index.


In [123]:
import time
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Assuming 'model' and 'tokenizer' are already defined and loaded
text = "total duration of"
num_predictions = 10
max_sequence_length = 56  # Adjust based on your model's input requirement

for i in range(num_predictions):
    # Tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    print(f"Tokenized text: {token_text}")

    # Padding
    padded_token_text = pad_sequences([token_text], maxlen=max_sequence_length, padding='pre')
    print(f"Padded token text: {padded_token_text}")

    # Predict
    prediction = model.predict(padded_token_text)
    print(f"Prediction: {prediction}")
    pos = np.argmax(prediction, axis=-1)[0]  # Get the index of the predicted word
    print(f"Predicted position: {pos}")

    # Find the word corresponding to the predicted index
    predicted_word = None
    for word, index in tokenizer.word_index.items():
        if index == pos:
            predicted_word = word
            break

    if predicted_word:
        text = text + " " + predicted_word
        print(f"Updated text: {text}")
    else:
        print("Predicted word not found in the tokenizer's word index.")
        break

    time.sleep(1)


Tokenized text: [70, 71, 6]
Padded token text: [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0 70 71  6]]
1/1 [==============================] - 0s 37ms/step
Prediction: [[1.77348682e-06 7.39435494e-01 5.71531476e-03 1.76126510e-02
  4.94484836e-03 2.58988421e-02 1.69936754e-02 6.18874049e-03
  3.04069906e-03 4.75717429e-03 5.00566186e-03 7.47147074e-04
  5.81571367e-03 2.45395256e-03 2.07577180e-03 2.20036646e-03
  1.28461225e-02 8.02031311e-04 2.73283315e-03 3.66266910e-03
  8.56061932e-03 1.99522707e-03 1.21208024e-03 1.39234914e-03
  2.43502040e-03 4.37775860e-03 1.95816276e-03 1.35863316e-03
  5.86438226e-04 7.64447250e-05 2.83454289e-03 6.96716248e-04
  3.96214251e-04 6.02673681e-04 3.84706934e-03 2.06524716e-03
  1.72565435e-03 1.51555624e-03 1.91401469e-03 7.43751414e-03
  2.80321779e-04 1.71320757e-03 1.18177175e-03 1.01787923e-03
  1.74231303e-03 8.19575100e-04

we can improve performance -
1. more data
2. hyperparameter tuning, increase or decrease nodes, epochs
3. we can use stacked, bidirectional lstm